### ISSUE TITLE
Правила работы с GitHub

### ISSUE THREAD

**Issue by TorinAsakura** [atls-academy/template#13]
# Правила работы с GitHub

Для более эффективной работы, мы в своей команде используем Github. Для нас GitHub это место где находится вся необходимая информация для работы и место где находится **истина** — код.

Github в нашей команде используют все: разработчики, дизайнеры, менеджеры, заказчики и все все все. Все находятся в одной среде и все всё видят. И это прекрасно. Но для того чтобы использовать GitHub эффективно, к нему надо привыкнуть и его надо  освоить.

В этом кратком руководстве, мы собрали **собственные командные практики работы с GitHub.** Также здесь есть ссылки на официальные руководства GitHub для расширения кругозора.

## Работа с Issues

Issues — это место где мы обсуждаем всю важную работу, от начала (создание issue) и до конца (закрытие issue).

Важно чтобы обсуждение по той или иной задаче/проблеме проходило внутри Issue. Это позволяет отследить историю в случае возникновения такой проблемы, а также даёт возможность просто делиться ссылкой на Issue или конкретный комментарий внутри Issue.

[Об Issues на GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)

### Issue Labels

Сам по себе Issue не несёт никакого «смыслового окраса». Для этого, мы применяем лейблы.

Например:

- Issue с лейблом *documents* — это задача или проблема, которая относится к документации
- Issue с лейблом *feature* — означает что там лежит какая-то информация о фиче
- Issue с лейблом *bug*, ну ты понял

Поэтому ***очень желательно***, чтобы Issues не оставались без лейблов. Список доступных лейблов доступен с правой стороны Issue, заголовок Labels:

![add label](https://docs.github.com/assets/cb-29833/images/help/issues/labels-drop-down.png)

[Управление Лейблами на GitHub Docs](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels)

### Отдельно про Markdown

Markdown — это облегчённый язык разметки. Эта разметка позволяет сделать текст **жирным** или *наклонным (италик)*.

Делать удобные для отображения списки:

- Раз
- Два
- Три

А также цитировать своих собеседников:

> Привет! Всё готово к релизу, погнали?

> Чел, сегодня пятница, какой релиз :|

Весь этот набор разметки, позволяет сделать самое главное: **писать красивые и чётко сформулированные мысли в текстовом виде.**

Это очень важно для командной работы. Потому что текст в Issues потеряется в самую последнюю очередь. А хорошо сформулированная мысль, позволит быстро донести суть до своих собеседников.

Поэтому важно ознакомиться с [Основным синтаксисом письма и форматирования Markdown на GitHub Docs.](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) Там же есть секция с продвинутыми практиками.

## Работа с Branches

*Стоит ли всё-таки оставлять эту секцию или нет? Мне непонятно.*

## Работа с Pull Request

> Pull Requests позволяют вам сообщить другим об изменениях, которые вы внесли в ветку в репозитории на GitHub. После открытия Pull Request'а вы можете обсудить и просмотреть потенциальные изменения с коллегами и добавить последующие коммиты до того, как ваши изменения будут объединены в базовую ветку.

[Из документации к Pull Request'ам на GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

### Как создавать?

[Создание Pull Request'а на Github Docs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

### Когда создавать?

Можно сразу после первых коммитов. Ежедневно, к концу рабочего дня должно коммититься текущее состояние вашей ветки. Если пр не готов к ревью - он отправляется в драфт (также по этой причине нет смысла использовать WIP в коммит месседжах: если работа в процессе - пр находится в драфте)

Это необходимо для прозрачности процесса, чтобы вовремя выявить недочеты при написании кода, пока кодовая база вокруг них не разрослась, они не остались незамеченными и не превратились в легаси.

В будущем такой подход также помогает при навигации по истории коммитов.

### Кого ставить в assignee?

Указываем себя, как автора. Это позволит потом по PR делать фильтрацию и получает предсказуемые результаты.

### Кого указывать в ревьюверах?

Лида (ментора) или если таковой отсутствует - @torinasakura

### Что за статусы проверок?

У проектов могут быть настроены проверки проектов, которые выполняются при создании и обновлении Pull Request'а. В них можно получить всю необходимую информацию о выполнении тестов.

### Можно ли форсить ветку? *(Нужна ли эта секция? Не слишком всё усложняет на данном этапе?)*

Можно, но только если от этого больше пользы, чем вреда. Когда можно:

1. Когда ревью еще не провели.
2. Когда в ветку еще ничего не вливали (обновленный dev)
3. Когда PR на этой ветке еще нет.

Когда нельзя:

1. Когда ревью провели. Комментарии привязываются к хешу коммитов. Если форснуть, то это уже новые коммиты, даже если в них ничего не менялось. Из-за этого весь прогресс ревью тупо слетает. В итоге ревьюверу нужно потратить время, чтобы определиться, где он оставлял ревью, а где нет.
2. Когда форсом можно ненароком ввести в заблуждение. После форса достаточно муторно посмотреть, что же в итоге изменилось. Можно, конечно, выдрать хеши и пойти в diff, чтобы посмотреть, что изменилось.

Лучше пусть будут лишние коммиты (коммиты лишними не бывают), так процесс выглядит более прозрачным и последовательным.

## Conventional Commits или Соглашение о коммитах

> «Соглашение о коммитах» — простое соглашение о том, как нужно писать сообщения коммитов. Оно описывает простой набор правил для создания понятной истории коммитов, а также позволяет проще разрабатывать инструменты автоматизации, основанные на истории коммитов.

[Цитата из официального документа соглашения](https://www.conventionalcommits.org/ru/v1.0.0/)

Мы придерживаемся данного [соглашения](https://www.conventionalcommits.org/ru/v1.0.0/) и **требуем** этого от всех разработчиков, членов нашей команды. Поэтому данное соглашение нужно изучить и соблюдать в своей работе.

## Post Scriptum

Эффективная работа в GitHub для нас очень важна. Здесь протекает вся рабочая «жизнь» проектов над которыми мы работаем. Поэтому для нас важно, чтобы каждый соблюдал базовые правила работы с этим инструментом.

Вообще, у GitHub довольно обширная и полезная [документация](https://docs.github.com/en), с которой рекомендуется ознакомиться.

Если незнаком или мало опыта с Git, то вот [полезный тур на русском языке](https://githowto.com/ru) по нему. [Чёрт побери, Git!?!](https://dangitgit.com/ru) быстрая и понятная подсказка по Git'у. Или [Интерактивная визуализация и учебник по Git.](https://github.com/pcottle/learnGitBranching)

**Comment by archeon-atls** [comment]
Статус?
